# Site settings
title: "Mario Russo"
description: > # this means to ignore newlines until "baseurl:"
  Mario Russo's cv hosted on GitHub.
baseurl: "/cv/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
linkedin_username: dotMR
github_username:  dotMR

# Build settings
markdown: kramdown

left-col-width: "14%"
right-col-width: "24%"
